# permissions for end users to view accesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesstoken-viewer-role
rules:
- apiGroups:
  - pipeline.buildkite.alam0rt.io
  resources:
  - accesstokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipeline.buildkite.alam0rt.io
  resources:
  - accesstokens/status
  verbs:
  - get
