# permissions for end users to view organizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: organization-viewer-role
rules:
- apiGroups:
  - pipeline.buildkite.alam0rt.io
  resources:
  - organizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipeline.buildkite.alam0rt.io
  resources:
  - organizations/status
  verbs:
  - get
