// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessToken) DeepCopyInto(out *AccessToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessToken.
func (in *AccessToken) DeepCopy() *AccessToken {
	if in == nil {
		return nil
	}
	out := new(AccessToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenList) DeepCopyInto(out *AccessTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenList.
func (in *AccessTokenList) DeepCopy() *AccessTokenList {
	if in == nil {
		return nil
	}
	out := new(AccessTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenSpec) DeepCopyInto(out *AccessTokenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenSpec.
func (in *AccessTokenSpec) DeepCopy() *AccessTokenSpec {
	if in == nil {
		return nil
	}
	out := new(AccessTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessTokenStatus) DeepCopyInto(out *AccessTokenStatus) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]Scope, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessTokenStatus.
func (in *AccessTokenStatus) DeepCopy() *AccessTokenStatus {
	if in == nil {
		return nil
	}
	out := new(AccessTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitbucketSettings) DeepCopyInto(out *BitbucketSettings) {
	*out = *in
	if in.BuildPullRequests != nil {
		in, out := &in.BuildPullRequests, &out.BuildPullRequests
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterEnabled != nil {
		in, out := &in.PullRequestBranchFilterEnabled, &out.PullRequestBranchFilterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterConfiguration != nil {
		in, out := &in.PullRequestBranchFilterConfiguration, &out.PullRequestBranchFilterConfiguration
		*out = new(string)
		**out = **in
	}
	if in.SkipPullRequestBuildsForExistingCommits != nil {
		in, out := &in.SkipPullRequestBuildsForExistingCommits, &out.SkipPullRequestBuildsForExistingCommits
		*out = new(bool)
		**out = **in
	}
	if in.BuildTags != nil {
		in, out := &in.BuildTags, &out.BuildTags
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatus != nil {
		in, out := &in.PublishCommitStatus, &out.PublishCommitStatus
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatusPerStep != nil {
		in, out := &in.PublishCommitStatusPerStep, &out.PublishCommitStatusPerStep
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitbucketSettings.
func (in *BitbucketSettings) DeepCopy() *BitbucketSettings {
	if in == nil {
		return nil
	}
	out := new(BitbucketSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnterpriseSettings) DeepCopyInto(out *GitHubEnterpriseSettings) {
	*out = *in
	if in.BuildPullRequests != nil {
		in, out := &in.BuildPullRequests, &out.BuildPullRequests
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterEnabled != nil {
		in, out := &in.PullRequestBranchFilterEnabled, &out.PullRequestBranchFilterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterConfiguration != nil {
		in, out := &in.PullRequestBranchFilterConfiguration, &out.PullRequestBranchFilterConfiguration
		*out = new(string)
		**out = **in
	}
	if in.SkipPullRequestBuildsForExistingCommits != nil {
		in, out := &in.SkipPullRequestBuildsForExistingCommits, &out.SkipPullRequestBuildsForExistingCommits
		*out = new(bool)
		**out = **in
	}
	if in.BuildTags != nil {
		in, out := &in.BuildTags, &out.BuildTags
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatus != nil {
		in, out := &in.PublishCommitStatus, &out.PublishCommitStatus
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatusPerStep != nil {
		in, out := &in.PublishCommitStatusPerStep, &out.PublishCommitStatusPerStep
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnterpriseSettings.
func (in *GitHubEnterpriseSettings) DeepCopy() *GitHubEnterpriseSettings {
	if in == nil {
		return nil
	}
	out := new(GitHubEnterpriseSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSettings) DeepCopyInto(out *GitHubSettings) {
	*out = *in
	if in.TriggerMode != nil {
		in, out := &in.TriggerMode, &out.TriggerMode
		*out = new(string)
		**out = **in
	}
	if in.BuildPullRequests != nil {
		in, out := &in.BuildPullRequests, &out.BuildPullRequests
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterEnabled != nil {
		in, out := &in.PullRequestBranchFilterEnabled, &out.PullRequestBranchFilterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PullRequestBranchFilterConfiguration != nil {
		in, out := &in.PullRequestBranchFilterConfiguration, &out.PullRequestBranchFilterConfiguration
		*out = new(string)
		**out = **in
	}
	if in.SkipPullRequestBuildsForExistingCommits != nil {
		in, out := &in.SkipPullRequestBuildsForExistingCommits, &out.SkipPullRequestBuildsForExistingCommits
		*out = new(bool)
		**out = **in
	}
	if in.BuildPullRequestForks != nil {
		in, out := &in.BuildPullRequestForks, &out.BuildPullRequestForks
		*out = new(bool)
		**out = **in
	}
	if in.PrefixPullRequestForkBranchNames != nil {
		in, out := &in.PrefixPullRequestForkBranchNames, &out.PrefixPullRequestForkBranchNames
		*out = new(bool)
		**out = **in
	}
	if in.BuildTags != nil {
		in, out := &in.BuildTags, &out.BuildTags
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatus != nil {
		in, out := &in.PublishCommitStatus, &out.PublishCommitStatus
		*out = new(bool)
		**out = **in
	}
	if in.PublishCommitStatusPerStep != nil {
		in, out := &in.PublishCommitStatusPerStep, &out.PublishCommitStatusPerStep
		*out = new(bool)
		**out = **in
	}
	if in.FilterEnabled != nil {
		in, out := &in.FilterEnabled, &out.FilterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FilterCondition != nil {
		in, out := &in.FilterCondition, &out.FilterCondition
		*out = new(string)
		**out = **in
	}
	if in.SeparatePullRequestStatuses != nil {
		in, out := &in.SeparatePullRequestStatuses, &out.SeparatePullRequestStatuses
		*out = new(bool)
		**out = **in
	}
	if in.PublishBlockedAsPending != nil {
		in, out := &in.PublishBlockedAsPending, &out.PublishBlockedAsPending
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSettings.
func (in *GitHubSettings) DeepCopy() *GitHubSettings {
	if in == nil {
		return nil
	}
	out := new(GitHubSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabSettings) DeepCopyInto(out *GitLabSettings) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabSettings.
func (in *GitLabSettings) DeepCopy() *GitLabSettings {
	if in == nil {
		return nil
	}
	out := new(GitLabSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.PipelinesURL != nil {
		in, out := &in.PipelinesURL, &out.PipelinesURL
		*out = new(string)
		**out = **in
	}
	if in.AgentsURL != nil {
		in, out := &in.AgentsURL, &out.AgentsURL
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.WebURL != nil {
		in, out := &in.WebURL, &out.WebURL
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pipeline.
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineList) DeepCopyInto(out *PipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineList.
func (in *PipelineList) DeepCopy() *PipelineList {
	if in == nil {
		return nil
	}
	out := new(PipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ProviderSettings.DeepCopyInto(&out.ProviderSettings)
	if in.TeamUuids != nil {
		in, out := &in.TeamUuids, &out.TeamUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSpec.
func (in *PipelineSpec) DeepCopy() *PipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStatus) DeepCopyInto(out *PipelineStatus) {
	*out = *in
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.WebURL != nil {
		in, out := &in.WebURL, &out.WebURL
		*out = new(string)
		**out = **in
	}
	if in.BuildsURL != nil {
		in, out := &in.BuildsURL, &out.BuildsURL
		*out = new(string)
		**out = **in
	}
	if in.BadgeURL != nil {
		in, out := &in.BadgeURL, &out.BadgeURL
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ArchivedAt != nil {
		in, out := &in.ArchivedAt, &out.ArchivedAt
		*out = (*in).DeepCopy()
	}
	if in.ScheduledBuildsCount != nil {
		in, out := &in.ScheduledBuildsCount, &out.ScheduledBuildsCount
		*out = new(int)
		**out = **in
	}
	if in.RunningBuildsCount != nil {
		in, out := &in.RunningBuildsCount, &out.RunningBuildsCount
		*out = new(int)
		**out = **in
	}
	if in.ScheduledJobsCount != nil {
		in, out := &in.ScheduledJobsCount, &out.ScheduledJobsCount
		*out = new(int)
		**out = **in
	}
	if in.RunningJobsCount != nil {
		in, out := &in.RunningJobsCount, &out.RunningJobsCount
		*out = new(int)
		**out = **in
	}
	if in.WaitingJobsCount != nil {
		in, out := &in.WaitingJobsCount, &out.WaitingJobsCount
		*out = new(int)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(Provider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStatus.
func (in *PipelineStatus) DeepCopy() *PipelineStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	if in.WebhookURL != nil {
		in, out := &in.WebhookURL, &out.WebhookURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSettings) DeepCopyInto(out *ProviderSettings) {
	*out = *in
	in.GitHubSettings.DeepCopyInto(&out.GitHubSettings)
	in.GitHubEnterpriseSettings.DeepCopyInto(&out.GitHubEnterpriseSettings)
	in.BitbucketSettings.DeepCopyInto(&out.BitbucketSettings)
	in.GitLabSettings.DeepCopyInto(&out.GitLabSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSettings.
func (in *ProviderSettings) DeepCopy() *ProviderSettings {
	if in == nil {
		return nil
	}
	out := new(ProviderSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Scopes) DeepCopyInto(out *Scopes) {
	{
		in := &in
		*out = make(Scopes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scopes.
func (in Scopes) DeepCopy() Scopes {
	if in == nil {
		return nil
	}
	out := new(Scopes)
	in.DeepCopyInto(out)
	return *out
}
